### ISSUE TITLE
"id" is now a reserved field name in Terraform

### ISSUE THREAD

**Issue by bonifaido** [softlayer/terraform-provider-softlayer#178] opened 2017-10-13 09:46 UTC
This happens when using Terraform 0.10.7:

1 error(s) occurred:

* provider.softlayer: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

19 error(s) occurred:

* resource softlayer_block_storage: id is a reserved field name for a resource
* resource softlayer_virtual_guest: id is a reserved field name for a resource
* resource softlayer_dns_domain_record: id is a reserved field name for a resource
* resource softlayer_scale_policy: id is a reserved field name for a resource
* resource softlayer_bare_metal: id is a reserved field name for a resource
* resource softlayer_lb_vpx_ha: id is a reserved field name for a resource
* resource softlayer_dns_secondary: id is a reserved field name for a resource
* resource softlayer_dns_domain: id is a reserved field name for a resource
* resource softlayer_lb_vpx_service: id is a reserved field name for a resource
* resource softlayer_security_certificate: id is a reserved field name for a resource
* resource softlayer_basic_monitor: id is a reserved field name for a resource
* resource softlayer_ssh_key: id is a reserved field name for a resource
* resource softlayer_objectstorage_account: id is a reserved field name for a resource
* resource softlayer_file_storage: id is a reserved field name for a resource
* resource softlayer_scale_group: id is a reserved field name for a resource
* resource softlayer_vlan: id is a reserved field name for a resource
* resource softlayer_provisioning_hook: id is a reserved field name for a resource
* resource softlayer_global_ip: id is a reserved field name for a resource
* resource softlayer_user: id is a reserved field name for a resource

**Comment by renier** [comment] 2017-10-13 13:08
Duplicate of #177

**Closed as completed by renier** 2017-10-13 13:08 UTC
